version: "3"
services:
  poly:
    image: 933060838752.dkr.ecr.eu-west-1.amazonaws.com/ofer:polybot
    
    container_name: poly
    
    ports:
      - 8443:8443
      
    volumes:
      # - ./YOURPRIVATE.key:/app/YOURPRIVATE.key
      # - ./YOURPUBLIC.pem:/app/YOURPUBLIC.pem
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials
      #C:\Users\User\.aws\credentials
      # - ./polybot/bot.py:/app/bot.py
      # - ./polybot/app.py:/app/app.py
      
    restart: always
